# Generated by Django 5.0.3 on 2024-05-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_ticket_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='sales_status',
            field=models.CharField(choices=[('Available', 'Available'), ('Sold Out', 'Sold Out')], max_length=20),
        ),
    ]
